### ISSUE TITLE
Geen alarm of beweging sinds HP2023

### ISSUE THREAD

**Issue by groetsels** [daneedk/com.amazon.ring#9] opened 2023-07-25 10:46 UTC
Hoi Danee,
Sinds mijn overgang naar HP2023 krijg ik geen meldingen meer binnen van de alarmen of bewegingen van de RING.
Home assistent geeft deze nog wel, en ook mijn android app geeft meldingen.
Ik heb 6 dagen geleden mijn bel opnieuw als apparaat toegevoegd.
Diagnose: c4eed5b7-c309-40d0-8704-77dfa6d89e37
Welke mogelijkheden zijn er om te testen?
![ring_homey2](https://github.com/daneedk/com.amazon.ring/assets/24290378/087b5249-55ea-42c4-9f7e-cfd37ba532f1)
![ring_homey](https://github.com/daneedk/com.amazon.ring/assets/24290378/8c003d78-69ad-4956-b3ce-81f585fc9179)
![ring_HA_2](https://github.com/daneedk/com.amazon.ring/assets/24290378/5fca98ff-c7ac-4f0e-b91f-92d4ec8ea967)
![ring_HA](https://github.com/daneedk/com.amazon.ring/assets/24290378/b87c61ea-a1a5-4838-8cfa-3a1938a7e852)
![ring_homey4](https://github.com/daneedk/com.amazon.ring/assets/24290378/73496ad4-f869-44b3-871f-7735adb6e146)
![ring_homey3](https://github.com/daneedk/com.amazon.ring/assets/24290378/41aa3be0-499f-4b93-adf7-84e704fc6ec5)

**Comment by daneedk** [comment] 2023-07-25 17:22
Hi Carel,

The best way to get support when experiencing is here: https://community.homey.app/t/ring-doorbell-and-camera-support-for-homey/76364

This particular problem you are experiencing is caused by changes in the Ring API and is described in the FAQ in that forum topic.
The fix for this is described here: https://community.homey.app/t/ring-doorbell-and-camera-support-for-homey/76364/5

For some users it was not enough to just delete the mentioned devices, they needed to use the **Remove All Devices** function in the Ring app to fix this.

**Closed by daneedk** 2023-07-25 17:22 UTC
